config/routes.rb
Rails.application.routes.draw do
  resources :instructors
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
 
  get 'auth/failure', to: redirect('/')

  devise_for :users, :controllers => {omniauth_callbacks: "users/omniauth_callbacks"} do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end
  
  get ':category_id/courses', to: "courses#byCategory", as: :coursesByCategory
  
  get 'pages/about'

  get 'pages/contact'
  
  get 'pages/categories'

  get 'home' => "enrollments#home"

  get ':id/classroom', to: "courses#classroom", as: :classroom

resources :courses do
    collection do
      get 'search'
    end
    resources :shortlists
  end

  resources :courses do
    resources :reviews, except: [:show, :index]
  end

  resources :courses do
    resources :enrollments, only: [:new, :create]
  end

  resources :sections do
        resources :videos, only: [:index, :new, :create]
  end

  resources :courses do
      resources :sections 
  end

  resources :categories do
    resources :courses
  end

  root 'pages#homepage'

end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
	if Rails.env.development?
		has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "defaults.jpeg"
  	else
  		has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "default.jpeg",
						:storage => :dropbox,
	    				:dropbox_credentials => Rails.root.join("config/dropbox.yml"),
	    				:path => ":style/:id_:filename"
	end
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  has_many :courses
end

app/controllers/instructors_controller.rb
class InstructorsController < InheritedResources::Base

  private

    def instructor_params
      params.require(:instructor).permit(:name, :details, :avatar)
    end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_form.html.erb
<%= simple_form_for(@instructor, :html => { :multipart => true }) do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <%= f.input :name %>
    <%= f.input :details %>
   
  </div>
  <div class="form-group">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar, class: 'form-control' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/instructors/edit.html.erb
<h1>Editing instructor</h1>

<%= render 'form' %>

<%= link_to 'Show', @instructor %> |
<%= link_to 'Back', instructors_path %>

app/views/instructors/index.html.erb
<h1>Listing instructors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Details</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instructors.each do |instructor| %>
      <tr>
        <td><%= instructor.name %></td>
        <td><%= instructor.details %></td>
        <td><%= link_to 'Show', instructor %></td>
        <td><%= link_to 'Edit', edit_instructor_path(instructor) %></td>
        <td><%= link_to 'Destroy', instructor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Instructor', new_instructor_path %>

app/views/instructors/new.html.erb
<h1>New instructor</h1>

<%= render 'form' %>

<%= link_to 'Back', instructors_path %>

app/views/instructors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @instructor.name %>
</p>

<p>
  <strong>Details:</strong>
  <%= @instructor.details %>
</p>
<%= image_tag @instructor.avatar.url %>
<%= image_tag @instructor.avatar.url(:medium) %>
<%= image_tag @instructor.avatar.url(:thumb) %>


<%= link_to 'Edit', edit_instructor_path(@instructor) %> |
<%= link_to 'Back', instructors_path %>