config/routes.rb
Rails.application.routes.draw do
  resources :instructors
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
 
  get 'auth/failure', to: redirect('/')

  devise_for :users, :controllers => {omniauth_callbacks: "users/omniauth_callbacks"} do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end
  
  get ':category_id/courses', to: "courses#byCategory", as: :coursesByCategory
  
  get 'pages/about'

  get 'pages/contact'
  
  get 'pages/categories'

  get 'home' => "enrollments#home"

  get ':id/classroom', to: "courses#classroom", as: :classroom

resources :courses do
    collection do
      get 'search'
    end
    resources :shortlists
  end

  resources :courses do
    resources :reviews, except: [:show, :index]
  end

  resources :courses do
    resources :enrollments, only: [:new, :create]
  end

  resources :sections do
        resources :videos, only: [:index, :new, :create]
  end

  resources :courses do
      resources :sections 
  end

  resources :categories do
    resources :courses
  end

  root 'pages#homepage'

end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base

	belongs_to :course
	belongs_to :user
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < InheritedResources::Base
	before_action :authenticate_user!


	def home
    	@enrollments = Enrollment.where(user: current_user).order("created_at DESC")
  	end


	def new
		@enrollment = Enrollment.new
		@course = Course.find(params[:course_id])

	end

	def create
		@enrollment = Enrollment.new
		@course = Course.find(params[:course_id])
		@enrollment.course_id = @course.id
		@enrollment.user_id = current_user.id	
		respond_to do |format|
	      	if @enrollment.save
	      		format.html {redirect_to action: :home, notice: "Thank you for enrolling in this course."}
	      		format.json {render action: 'show', status: :created, location: @enrollment}
	      	else
	      		format.html {render action: 'new'}
	      		format.json {render json: @enrollment.errors, status: :unprocessable_entity}
	      	end
      	end
	end
  private

    def enrollment_params
      params.require(:enrollment).permit(:user_id, :course_id)

    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/home.html.erb
<div class="subhead">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="text2 shape">

                </div>
            </div>
            <div class="col-lg-4">
                <div class="box2">
                    <input type="search" class="form-control"/>
                </div>
                <button class="btn box3 search">
                    Search
                </button>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h2>Most Popular Courses</h2>

            <div class="clearfix">
                <div class="col-lg-12 bgec pl0 pr0">
                    <ul class="list-inline font13 dashNav">
                        <li class="active">
                           <a href="#"> LEARNING</a>
                        </li>
                        <li>
                            <a href="#"> WISHLIST</a>
                        </li>
                        <li>
                            <a href="#"> LEADERBOARD</a>
                        </li>
                        <li>
                            <a href="#">COMPLETED</a>
                        </li>
                    </ul>

                </div>

            </div>
        </div>
    </div>
    <div class="row">
        <% @enrollments.each do |enrollment| %>
        <div class="col-lg-3 ">
            <div class="clearfix">
                <div class="col-lg-12 bgLinkColor mt15">
                    <div class="row">
                        <div class="col-lg-8 pr0">
                            <div class="progressDiv pt15 pb15">
                                <div class="progress m0">
                                    <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0"
                                         aria-valuemax="100" style="width: 60%;">
                                        <span>60% Complete</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 colorfff font11 pt15 pl0 pr0 tac">
                            12mins 30sec
                        </div>

                    </div>

                </div>
            </div>
            <div class="courseBox">
            <div class="clearfix">
                <div class="col-lg-12 bgF6 pt10 courseDetails pr10 pl10">
                    <h4 class="m0 pb10"><%= enrollment.course.name %></h4>
                    <%= image_tag enrollment.course.image.url, :alt => "yoga", :class => "yoga" %>

                    <span class="font12">Added on <%=enrollment.course.created_at%></span>

                    <div class="courseDesc">
                        <%= enrollment.course.description %>
                    </div>
                    <div class="pt5 pb5">
                        <strong>Teacher</strong>: <%= enrollment.course.instructor.name %>
                    </div>
                    <div class="mask"></div>
                </div>
            </div>
            <div class="clearfix">
                <div class="col-lg-12 bgF6 courseInfo">
                    <div class="row">
                        <div class="col-lg-6 pt8 pb8">
                            <%= button_to "Resume", classroom_path(enrollment.course), class: 'btn btn-sm btn-primary'%>

                        </div>
                        <div class="col-lg-6 pt8 pb8">
                            <%=enrollment.course.level%>
                        </div>

                    </div>

                </div>

            </div>
            </div>
        </div>

        <% end %>

    </div>

    <div class="clearfix col-lg-12 brt1 p0 mt15">
        <h3 class="mt15 mb5 colorLink">Recommended for you</h3>
    </div>

    <div class="row">
        <div class="col-lg-3 ">
            <div class="clearfix">
                <div class="col-lg-12 bgLinkColor mt15">
                    <div class="row">
                        <div class="col-lg-8 pr0">
                            <div class="progressDiv pt15 pb15">
                                <div class="progress m0">
                                    <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0"
                                         aria-valuemax="100" style="width: 60%;">
                                        <span>60% Complete</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 colorfff font11 pt15 pl0 pr0 tac">
                            12mins 30sec
                        </div>

                    </div>

                </div>
            </div>
            <div class="courseBox">
            <div class="clearfix">
                <div class="col-lg-12 bgF6 pt10 courseDetails">
                    <h4 class="m0 pb10">Bakasana (Crane Pose) Tutorial</h4>
                    <%= image_tag("yoga.png", :alt => "yoga", :class => "yoga") %>
                    <div class="mask"></div>
                    <span class="font12">Added on 02/02/2015</span>

                    <div>
                        Having a smooth and successful taking off into Bakasana is challenging for many yoga
                        practitioners!
                    </div>
                    <div class="pt5 pb5">
                        <strong>Teacher</strong>: Bikram Choudhury
                    </div>
                </div>
            </div>
            <div class="clearfix">
                <div class="col-lg-12 bgF6 courseInfo">
                    <div class="row">
                        <div class="col-lg-6 pt8 pb8">
                            <button class="btn btn-sm btn-primary">
                                Resume
                            </button>
                        </div>
                        <div class="col-lg-6 pt8 pb8">
                            Beginner
                        </div>

                    </div>

                </div>

            </div>
            </div>
        </div>
        <div class="col-lg-3 ">
            <div class="clearfix">
                <div class="col-lg-12 bgLinkColor mt15">
                    <div class="row">
                        <div class="col-lg-8 pr0">
                            <div class="progressDiv pt15 pb15">
                                <div class="progress m0">
                                    <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0"
                                         aria-valuemax="100" style="width: 60%;">
                                        <span>60% Complete</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 colorfff font11 pt15 pl0 pr0 tac">
                            12mins 30sec
                        </div>

                    </div>

                </div>
            </div>
            <div class="clearfix">
                <div class="col-lg-12 bgF6 pt10 courseDetails">
                    <h4 class="m0 pb10">Bakasana (Crane Pose) Tutorial</h4>
                    <%= image_tag("yoga.png", :alt => "yoga", :class => "yoga") %>
                    <span class="font12">Added on 02/02/2015</span>

                    <div>
                        Having a smooth and successful taking off into Bakasana is challenging for many yoga
                        practitioners!
                    </div>
                    <div class="pt5 pb5">
                        <strong>Teacher</strong>: Bikram Choudhury
                    </div>
                </div>
            </div>
            <div class="clearfix">
                <div class="col-lg-12 bgF6 courseInfo">
                    <div class="row">
                        <div class="col-lg-6 pt8 pb8">
                            <button class="btn btn-sm btn-primary">
                                Resume
                            </button>
                        </div>
                        <div class="col-lg-6 pt8 pb8">
                            Beginner
                        </div>

                    </div>

                </div>

            </div>

        </div>
        <div class="col-lg-3 ">
            <div class="clearfix">
                <div class="col-lg-12 bgLinkColor mt15">
                    <div class="row">
                        <div class="col-lg-8 pr0">
                            <div class="progressDiv pt15 pb15">
                                <div class="progress m0">
                                    <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0"
                                         aria-valuemax="100" style="width: 60%;">
                                        <span>60% Complete</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 colorfff font11 pt15 pl0 pr0 tac">
                            12mins 30sec
                        </div>

                    </div>

                </div>
            </div>
            <div class="clearfix">
                <div class="col-lg-12 bgF6 pt10 courseDetails">
                    <h4 class="m0 pb10">Bakasana (Crane Pose) Tutorial</h4>
                    <%= image_tag("yoga.png", :alt => "yoga", :class => "yoga") %>
                    <span class="font12">Added on 02/02/2015</span>

                    <div>
                        Having a smooth and successful taking off into Bakasana is challenging for many yoga
                        practitioners!
                    </div>
                    <div class="pt5 pb5">
                        <strong>Teacher</strong>: Bikram Choudhury
                    </div>
                </div>
            </div>
            <div class="clearfix">
                <div class="col-lg-12 bgF6 courseInfo">
                    <div class="row">
                        <div class="col-lg-6 pt8 pb8">
                            <button class="btn btn-sm btn-primary">
                                Resume
                            </button>
                        </div>
                        <div class="col-lg-6 pt8 pb8">
                            Beginner
                        </div>

                    </div>

                </div>

            </div>

        </div>
        <div class="col-lg-3 ">
            <div class="clearfix">
                <div class="col-lg-12 bgLinkColor mt15">
                    <div class="row">
                        <div class="col-lg-8 pr0">
                            <div class="progressDiv pt15 pb15">
                                <div class="progress m0">
                                    <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0"
                                         aria-valuemax="100" style="width: 60%;">
                                        <span>60% Complete</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 colorfff font11 pt15 pl0 pr0 tac">
                            12mins 30sec
                        </div>

                    </div>

                </div>
            </div>
            <div class="clearfix">
                <div class="col-lg-12 bgF6 pt10 courseDetails">
                    <h4 class="m0 pb10">Bakasana (Crane Pose) Tutorial</h4>
                    <%= image_tag("yoga.png", :alt => "yoga", :class => "yoga") %>
                    <span class="font12">Added on 02/02/2015</span>

                    <div>
                        Having a smooth and successful taking off into Bakasana is challenging for many yoga
                        practitioners!
                    </div>
                    <div class="pt5 pb5">
                        <strong>Teacher</strong>: Bikram Choudhury
                    </div>
                </div>
            </div>
            <div class="clearfix">
                <div class="col-lg-12 bgF6 courseInfo">
                    <div class="row">
                        <div class="col-lg-6 pt8 pb8">
                            <button class="btn btn-sm btn-primary">
                                Resume
                            </button>
                        </div>
                        <div class="col-lg-6 pt8 pb8">
                            Beginner
                        </div>

                    </div>

                </div>

            </div>

        </div>
    </div>

</div>

app/views/enrollments/index.html.erb
<h1>Listing enrollments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enrollments.each do |enrollment| %>
      <tr>
        <td><%= link_to 'Show', enrollment %></td>
        <td><%= link_to 'Edit', edit_enrollment_path(enrollment) %></td>
        <td><%= link_to 'Destroy', enrollment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enrollment', new_course_enrollment_path %>

app/views/enrollments/new.html.erb
<h1>New enrollment</h1>

<%= render 'form' %>

<%= link_to 'Back', enrollments_path %>